# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->


  $grid = $('#masonry-container').isotope(
    itemSelector: '.box'
    layoutMode: 'fitRows')
  
  $('.warm-ones').click ->
    $grid.isotope filter: '.warm'
    console.log("test")
    return

  $('.all').click ->
    $grid.isotope filter: '*'
    console.log("test")
    return

  return

# ---
# generated by js2coffee 2.2.0